<?php

/**
 * Implementation of hook_meu()
 */
function pp_piratenpad_menu() {
  $items = array();

  $items['admin/settings/piraten/piratenpad'] = array(
    'title' => 'Piratenpads',
    'description' => 'Team user und Darstellungs-Einstellungen',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('pp_piratenpad_admin_form'),
    'access arguments' => array('administer pp_piratenpad'),
    'file' => 'pp_piratenpad.admin.inc'
  );

  $items['admin/settings/piraten/piratenpad/settings'] = array(
    'title' => 'Settings',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  $items['admin/settings/piraten/piratenpad/update'] = array(
    'title' => 'Update Now',
    'page callback' => 'pp_piratenpad_update',
    'access arguments' => array('administer pp_piratenpad'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 1,
  );

  return $items;
}


/**
* Display help and module information.
* @param path
*   Which path of the site we're displaying help.
* @param arg
*   Array that holds the current path as would be returned from arg() function.
* @return
*   help text for the path.
*/
function pp_piratenpad_help($path, $arg) {
  $output = '';
  switch ($path) {
    case "admin/help#pp_piratenpad":
      $output = '<p>'. t("Zeigt den Block für alle aktuellen Piratenpads").'</p>';
      break;
  }
  return $output;
} // function pp_piratenpad_help


/**
* Valid permissions for this module
* @return array An array of valid permissions for the pp_piratenpad module
*/

function pp_piratenpad_perm() {
  return array('administer pp_piratenpad');
} // function pp_piratenpad_perm()


/**
* Generate HTML for the pp_piratenpad block
* @param op the operation from the URL
* @param delta offset
* @returns block HTML
*/
function pp_piratenpad_block($op='list', $delta=0) {
	// listing of blocks, such as on the admin/block page
		if ($op == "list") {
			$block[0]["info"] = "Piraten - ".t('Aktuelle Piratenpads');
			return $block;
		} else if ($op == 'view') {
			// our block content
				$max = variable_get('pp_piratenpad_max', 5);
				$sort_alpha = variable_get('pp_piratenpad_sort_alpha', TRUE);
				$sort_last_edited = variable_get('pp_piratenpad_sort_last_edited', FALSE);

				$sql = "SELECT * FROM {pp_piratenpad}";
				if ($sort_alpha && $sort_last_edited) {
					$sql .= " ORDER BY `last_edited` DESC, `name`";
				} else if ($sort_alpha) {
					$sql .= " ORDER BY `name`";
				} else if ($sort_last_edited) {
					$sql .= " ORDER BY `last_edited` DESC";
				}
				$sql .= " LIMIT 0, ".$max;

				$results = db_query($sql);

				$block_content	= '<ul class="menu">';
				while ($pad = db_fetch_array($results)) {
					$block_content .= "<li><a href='".$pad["url"]."'>".$pad["name"]."</a></li>";
				}
				$block_content = trim($block_content);
				$block_content = nl2br($block_content);

				$block_content .= "</ul><div style='width: 100%; text-align: right;'><a href='/piratenpad' title='Mehr'>&raquo; Mehr</a></div>";

			// set up the block
				$block['subject'] = t('Aktuelle Piratenpads');
				$block['content'] = $block_content;
				return $block;
		}
}

/**
*
*/
function pp_piratenpad_update() {
	// run cron
		pp_piratenpad_cron();

	// clear cache
		cache_clear_all(NULL, 'pp_piratenpad');

	// load
		$sql = "SELECT COUNT(*) AS `count` FROM {pp_piratenpad}";
		$result = db_query($sql);
		$data = db_fetch_array($result);

	// return
		return $data["count"]." ".t("pads inserted");
}

/**
*
*/
function pp_piratenpad_cron() {
	$url = variable_get('pp_piratenpad_url', NULL);
	$email = variable_get('pp_piratenpad_email', NULL);
	$password = variable_get('pp_piratenpad_password', NULL);

	$vars = array(
		"url" => $url,
		"email" => $email,
		"password" => $password,
	);

	$debug = false;

	if (!empty($url) && !empty($email) && !empty($password)) {
		// 0. prepare debug
			if ($debug) echo "<pre>";

		// 1. get the piratepad team cookies
			$_url = "https://".$url."/ep/account/sign-in?cont=https".urlencode("://".$url."/ep/padlist/all-pads");
			$_headers = array();
			$_data = array();

			$response = drupal_http_request($_url, $_headers, 'GET', http_build_query($_data), 0);
#			if ($debug) print_r($response);
#			if ($debug) die();
			$_team_cookie = $response->headers['Set-Cookie'];
			preg_match_all("/(E\w=\w*;)/", $_team_cookie, $regs);
#			if ($debug) print_r($regs);
			$_team_cookie = array_pop($regs[1]);
			$_cookie = trim($_team_cookie);
#			if ($debug) print_r($_cookie);
			$_headers = array('Cookie' => $_cookie);
			$_url = $response->headers['Location'];
#			if ($debug) die();

		// 2. get the piratepad cookie
			$response = drupal_http_request($_url, $_headers, 'GET', http_build_query($_data), 0);
#			if ($debug) print_r($response);
#			if ($debug) die();
			$_cookie = $response->headers['Set-Cookie'];
			preg_match_all("/(E\w=\w*;)/", $_cookie, $regs);
#			if ($debug) print_r($regs);
			$_cookie = trim($_team_cookie);
			foreach($regs[1] as $reg) {
				$_cookie .= " ".$reg;
			}
			$_cookie = trim($_cookie);
#			if ($debug) print_r($_cookie);
			$_headers = array('Cookie' => $_cookie);
			$_url = $response->headers['Location'];
#			if ($debug) die();

		// 3. get the 1st redirect to the login screen
			$response = drupal_http_request($_url, $_headers, 'GET', http_build_query($_data), 0);
#			if ($debug) print_r($response);
#			if ($debug) die();
			$_url = $response->headers['Location'];

		// 4. get the login screen
			$response = drupal_http_request($_url, $_headers, 'GET', http_build_query($_data), 0);
#			if ($debug) print_r($response);
#			if ($debug)die();

		// 5. do the login
#			if ($debug) print_r($_url);
			$_headers['Content-Type'] = "application/x-www-form-urlencoded";
			#$_url = "http://".$url."/ep/account/sign-in?cont=".urlencode("https://".$url."/ep/padlist/all-pads");
			#$_url = "http://".$url."/ep/account/sign-in?cont=".urlencode("https://".$url."/");
			$_data = array(
				"email" => $email,
				"password" => $password,
			);
#			if ($debug) print_r($_data);
			$response = drupal_http_request($_url, $_headers, 'POST', http_build_query($_data, '', '&'), 0);
#			if ($debug) print_r($response);
#			if ($debug) die();
			$_url = $response->headers['Location'];

		// 6. get the result page
			unset($_headers['Content-Type']);
			$_data = array();
			$response = drupal_http_request($_url, $_headers, 'GET', http_build_query($_data), 0);
#			if ($debug) print_r($response);
#			if ($debug) die();

			$pads = array();

			if (strpos($response->data, "padlock.gif") === false) {
				// no padlock
					preg_match_all("/<td\s*class=\"title first\">(.*)?<\//", $response->data, $regs);
			} else {
				// padlock found
					preg_match_all("/<td\s*class=\"title first\">(.*)?<\//", $response->data, $regs);
			}
#			if ($debug) print_r($regs);
#			if ($debug) die();

			foreach($regs[1] as $id => $reg) {
				preg_match_all("/(\/.*?)?\"/", $reg, $regs2);
#				if ($debug) print_r($regs2);
				$pads[$id] = array();
				$pads[$id]["name"] = strip_tags($reg);
				$pads[$id]["url"] = "http://".$url.$regs2[1][1];
			}

			preg_match_all("/<td\s*class=\"lastEditedDate\">(.*)?</", $response->data, $regs);
#			if ($debug) print_r($regs);
			foreach($regs[1] as $id => $reg) {
				$edited = strip_tags($reg);
				$edited = str_replace("ago", "", $edited);
				$edited = trim($edited);
				$edited = "- ".$edited;
				$pads[$id]["last_edited"] = strtotime($edited);
			}

			preg_match_all("/<td\s*class=\"editors\">(.*)?</", $response->data, $regs);
#			if ($debug) print_r($regs);
			foreach($regs[1] as $id => $reg) {
				$pads[$id]["editor"] = strip_tags($reg);
			}
#			if ($debug) print_r($pads);
#			if ($debug) die();

		// 8. sign out
			$_url = "https://".$url."/ep/account/sign-out";
			$response = drupal_http_request($_url, $_headers, 'GET', http_build_query($_data), 0);
#			if ($debug) print_r($response);
#			if ($debug) die();

		// 9. check pads public status
			foreach($pads as $id => $pad) {
#				if ($debug) print_r($pad);
				$url = str_replace("http://", "https://", $pad["url"]);
#				if ($debug) print_r($url);
				$response = drupal_http_request($url, $_headers, 'GET', http_build_query($_data), 0);
#				if ($debug) print_r($response->code);
#				if ($debug) print_r($response);
				if ($response->code != 200)
					unset($pads[$id]);
			}
#			if ($debug) print_r($pads);
#			if ($debug) die();

		// 10. store to database
			if (sizeof($pads) > 0)
				db_query("TRUNCATE TABLE {pp_piratenpad}");

			foreach($pads as $id => $pad) {
				drupal_write_record("pp_piratenpad", $pad);
				watchdog('pp_piratenpad', t("Pad: ".$pad["name"]));
			}

		// 11. stop debug
			if ($debug) echo "</pre>";
	} else {
		watchdog('pp_piratenpad', t("Cron run failed: Missing variables"), $vars, WATCHDOG_ERROR);
	}
}

?>
